name: Flutter Linux CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'

      - name: Enable Linux Desktop
        run: flutter config --enable-linux-desktop

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang cmake ninja-build pkg-config libgtk-3-dev dpkg-dev fakeroot

      - name: Install dependencies
        run: flutter pub get

      - name: Build for Linux
        run: flutter build linux

      - name: Package .deb file
        run: |
          mkdir -p dist/synapsis/DEBIAN
          mkdir -p dist/synapsis/usr/local/bin
          cp -r build/linux/x64/release/bundle/* dist/synapsis/usr/local/bin/

          cat <<EOF > dist/synapsis/DEBIAN/control
          Package: synapsis
          Version: 1.0.0
          Section: base
          Priority: optional
          Architecture: amd64
          Depends: libgtk-3-0
          Maintainer: Chairil Rafi chairilraffi@gmail.com
          Description: Synapsis.id
          EOF

          dpkg-deb --build dist/synapsis dist/synapsis.deb

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-linux-app-deb
          path: dist/synapsis.deb
